# main.py
"""
Leverage Matrix Analyzer CLI

Analyzes two CSV files:
  1. your_products.csv – columns: product_id, price, cost, category
  2. competitor_prices.csv – columns: product_id, competitor_price, competitor_name

The tool computes:
  • Price gap percentage
  • Gross margin and margin gap
  • Strategic leverage score (weighted combination)

Outputs a markdown report with top 5 high‑leverage opportunities and a JSON summary
that can be consumed by SaaS back‑ends.

Usage:
  python main.py your_products.csv competitor_prices.csv --output report.md
"""
import argparse
import csv
import json
import sys
from pathlib import Path
from typing import List, Dict, Any

def load_csv(path: Path) -> List[Dict[str, str]]:
    if not path.is_file():
        sys.exit(f"Error: file not found – {path}")
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def compute_metrics(your: List[Dict[str, str]], comp: List[Dict[str, str]]) -> List[Dict[str, Any]]:
    comp_index = {row["product_id"]: row for row in comp}
    results = []
    for row in your:
        pid = row["product_id"]
        if pid not in comp_index:
            continue
        try:
            price = float(row["price"])
            cost = float(row["cost"])
            comp_price = float(comp_index[pid]["competitor_price"])
        except ValueError:
            continue
        margin = (price - cost) / price if price else 0
        comp_margin = (comp_price - cost) / comp_price if comp_price else 0
        price_gap = ((comp_price - price) / price) * 100 if price else 0
        margin_gap = (comp_margin - margin) * 100
        # Leverage score: higher when price gap is positive (you can raise price) and margin gap is positive (you have better margin)
        leverage = (price_gap * 0.6) + (margin_gap * 0.4)
        results.append({
            "product_id": pid,
            "category": row.get("category", ""),
            "your_price": price,
            "competitor_price": comp_price,
            "price_gap_pct": round(price_gap, 2),
            "your_margin_pct": round(margin * 100, 2),
            "competitor_margin_pct": round(comp_margin * 100, 2),
            "margin_gap_pct": round(margin_gap, 2),
            "leverage_score": round(leverage, 2),
            "competitor_name": comp_index[pid].get("competitor_name", "")
        })
    return sorted(results, key=lambda x: x["leverage_score"], reverse=True)

def markdown_report(data: List[Dict[str, Any]], top_n: int = 5) -> str:
    lines = ["# Leverage Matrix Report", "", "## Top Opportunities"]
    lines.append("| Rank | Product ID | Category | Your Price | Competitor Price | Price Gap % | Your Margin % | Competitor Margin % | Leverage Score |")
    lines.append("|------|------------|----------|------------|------------------|------------|---------------|----------------------|----------------|")
    for i, row in enumerate(data[:top_n], 1):
        lines.append(
            f"| {i} | {row['product_id']} | {row['category']} | {row['your_price']:.2f} | {row['competitor_price']:.2f} | {row['price_gap_pct']:.2f}% | {row['your_margin_pct']:.2f}% | {row['competitor_margin_pct']:.2f}% | {row['leverage_score']:.2f} |"
        )
    lines.append("\n---\n")
    lines.append("*Generated by Leverage Matrix Analyzer*")
    return "\n".join(lines)

def main() -> None:
    parser = argparse.ArgumentParser(description="Leverage Matrix Analyzer")
    parser.add_argument("your_csv", type=Path, help="Path to your_products.csv")
    parser.add_argument("competitor_csv", type=Path, help="Path to competitor_prices.csv")
    parser.add_argument("--output", type=Path, default=Path("leverage_report.md"), help="Markdown report file")
    parser.add_argument("--json", type=Path, default=Path("leverage_summary.json"), help="JSON summary file")
    args = parser.parse_args()

    your_data = load_csv(args.your_csv)
    comp_data = load_csv(args.competitor_csv)

    analysis = compute_metrics(your_data, comp_data)
    if not analysis:
        sys.exit("No matching product IDs found between the two files.")

    md = markdown_report(analysis)
    args.output.write_text(md, encoding="utf-8")
    args.json.write_text(json.dumps(analysis, indent=2), encoding="utf-8")
    print(f"Report written to {args.output}\nJSON summary written to {args.json}")

if __name__ == "__main__":
    main()
